export const ADD_USERCATEGORY = "ADD_USERCATEGORY";
export const FETCH_USERCATEGORY = "FETCH_USERCATEGORY";
export const DELETE_USERCATEGORY = "DELETE_USERCATEGORY";
export const UPDATE_USERCATEGORY = "UPDATE_USERCATEGORY";
export const FETCH_IMAGE = "FETCH_IMAGE";
